"""initial schema: 6 tables

Revision ID: f5c64023b2d5
Revises: 
Create Date: 2026-09-10 02:29:36.434924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c64023b2d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_text', sa.Text(), nullable=False),
    sa.Column('overall_verdict', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('judgment_model', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("judgment_model IN ('frontier','fine_tuned')", name='ck_runs_model'),
    sa.CheckConstraint("status IN ('running','complete','failed')", name='ck_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('retrieval_enabled', sa.Boolean(), nullable=False),
    sa.Column('accuracy', sa.Numeric(), nullable=False),
    sa.Column('mrr', sa.Numeric(), nullable=False),
    sa.Column('ndcg', sa.Numeric(), nullable=False),
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.CheckConstraint("model IN ('frontier','fine_tuned')", name='ck_eval_model'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_log',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'request_date')
    )
    op.create_table('reference_kb_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reference_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.CheckConstraint("confidence IN ('normal','escalated')", name='ck_clauses_confidence'),
    sa.CheckConstraint("risk_level IN ('low','medium','high','unable_to_assess')", name='ck_clauses_risk'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent IN ('segmenter','retriever','judgment','verifier')", name='ck_audit_agent'),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_audit_log')
    op.drop_table('clauses')
    op.drop_table('reference_kb_entries')
    op.drop_table('rate_limit_log')
    op.drop_table('eval_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
